# Generated by Django 3.2.22 on 2023-11-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='create_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.CharField(max_length=30),
        ),
    ]
