# Generated by Django 3.2.22 on 2023-11-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20231105_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='cle_gl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('cre_date', models.CharField(max_length=30)),
                ('end_date', models.CharField(max_length=30)),
            ],
        ),
    ]
